services:
  slack-bot:
    build: 
      context: apps/slack-bot
      dockerfile: Dockerfile
      args:
        - PG_DATABASE_URL=${PG_DATABASE_URL}
        - GRAPHITE_HOST=${GRAPHITE_HOST}
    ports: 
      - "3001:3001"
    env_file: "scrappy.env"
    environment:
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - GRAPHITE_HOST=${GRAPHITE_HOST}
  scrapbook: 
    build: 
      context: apps/web
      dockerfile: Dockerfile
      args:
        - PG_DATABASE_URL=${PG_DATABASE_URL}
        - GRAPHITE_HOST=${GRAPHITE_HOST}
    ports:
      - "3002:3000"
    env_file: "scrappy.env"
    environment:
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - GRAPHITE_HOST=${GRAPHITE_HOST}
